# Generated by Django 6.1 on 2026-08-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('device_type', models.CharField(choices=[('network', 'Network monitor'), ('water', 'Water leak sensor'), ('fire', 'Fire/smoke sensor')], max_length=10)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('network', 'Network monitor'), ('water', 'Water leak sensor'), ('fire', 'Fire/smoke sensor')], max_length=10)),
                ('recorded_at', models.DateTimeField()),
                ('value', models.FloatField(default=0)),
                ('secondary_value', models.FloatField(blank=True, null=True)),
                ('reachable', models.BooleanField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='telemetry.devicekey')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
